# Automated testing with Travis CI!

os:
  - osx

language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

notifications:
  email:
    on_success: change
    on_failure: always

# This file was first created using the Yeoman generator
#  generator-hchiam-learning:
#  https://www.npmjs.com/package/generator-hchiam-learning
